# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LJScroView-master' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for LJScroView-master

pod "Masonry"
pod "SDWebImage"

  target 'LJScroView-masterTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'LJScroView-masterUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
